### PR TITLE
More code cleanup

### PR DESCRIPTION
**Pull request by twogee**
Your janitor is here again 😃

This drops commons-lang as test dependency, removes unused imports, simplifies if's and corrects a bunch of misspellings.

### CODE REVIEW

**Comment by janmaterne** [comment]
start reviewing

**Comment by janmaterne** [comment]
build.xml
- Nice idea with the copyright statement in Javadoc ( (c)${years} ; years=tstamp("2007-yyyy") ).

You found a lot of spell errors ;)

MatcherLookup.java#get(Map<String,String>): new Javadoc is:
  '@return a list of matchers that can apply to module withs specified attributes'
I am not sure about 'withs' or 'with' ...

Nice rewrites of 
  "myBoolean == null : false = myBoolean.booleanValue()" (and opposite) to
  "myBoolean != null && myBoolean"



For Discussion:
---------------
ModuleInSort.java, class javadoc, "is sorted": I think the 'iff' has a 'f' too much.



Problems:
---------
Fixing the spell error in DelegateHandler$ChildElementHandler (s/childHanlded/childHandled/) means breaking beakward compatiblity. 
We could introduce a delegetate for that:
  /** for BC */
  @Deprecated
  public void childHanlded(DH child) throws SAXParseException {
    childHandled(DH child);
  }
While refactoring you have renamed all occurences in the Ivy codebase. 
On the other hand I don't know the impact (maybe outside of Ivy). I'll bring that to the dev-list.

src/java/org/apache/ivy/osgi/repo/FSManifestIterable.java: renaming the public constant DEFAULT_BUNLDE_FILTER also means breaking BC.

src/java/org/apache/ivy/osgi/util/Version.java: the constructor removes the (IMO unneccessary) ParseException. But because it is a checked Exception we break BC.

renaming EncrytedProperties to EncryptedProperties means breaking BC. If required we could introduce a delegating class or a subclass.

ArtifactOrigin: renaming unkwnown() to unknown() means breaking BC. If required we could introduce a delegating method.

**Comment by janmaterne** [comment]
Because of the problems I dont merge this ATM. We should discuss them on the dev list before.

**Comment by janmaterne** [comment]
merged, thanks for the huge work.
What about the "iff"? I am not a native speaker and dont want to judge ;)

**Comment by nlalevee** [comment]
In french we have "ssi" which is a contraction of "si et seulement si" which has a mathematical meaning about absolute equivalence between two propositions.
I bet that in english "iff" means then "if and only if".

**Comment by janmaterne** [comment]
You're right. I looked at a dictionary. I'll change that, so haven't to think about that in the future. ;)

**Pull request merged**
