### PR TITLE
Generics and related fixes in tests and tutorials

### PR DESCRIPTION
**Pull request by twogee**
foreach loops are more terse than iterators, and they go well together with generic -- here's the first stab 😃

### CODE REVIEW

**Comment by janmaterne** [comment]
Java7 supports the diamond operator and Ivy's baseline is now Java7. So you could use that (e.g. CCFilter.java).

HMFilter: one advantage of foreach is having a meaningful iterator name. So renaming s/string/value/ would be more readable.

HelloIvy: maybe you could change the hello-message: s/hello ivy !/Hello Ivy!/

src/example/multi-project/projects/find/src/find/Main.java: maybe also change from raw Collection to Collection<File>, so the foreach could also be typed. This would impact FindFile.
--> better in a separate PR

Same for src/example/multi-project/projects/list/src/list/Main.java
--> better in a separate PR

Same src/example/multi-project/projects/size/src/size/FileSize.java
--> better in a separate PR

test/java/org/apache/ivy/core/module/id/ModuleIdTest.java
You changed the semantics:
  assertFalse(moduleId.equals(null)) --> asserts that moduleId is not null (otherwise a NPE would be thrown) and it's equal-comparison returns false
  assertNotNull(moduleId) --> 'just' assert that moduleId is not null
--> maybe just place the notnull before the assertfalse?

**Comment by twogee** [comment]
Thank you for comments, I'll split the PR and correct according to your suggestions. Should I remove common-colections altogether and use collections with generics from Java runtime?

**Comment by janmaterne** [comment]
I wont split this PR. Adress these in this PR:
- diamond operator
- renaming
- ModuleIdTest

The other things should be done in a new PR (PRs shouldnt be too big ;)
I wouldnt remove commons-collections as it is an example how to use external libs with Ivy.

**Comment by twogee** [comment]
Here comes a bunch of new changes: I had to go for Commons Collections 4 to use generics, and threw in Commons CLI 1.4 for a good measure. I left HTTP Client 2.0 for the future lest this PR grows further 😃

**Comment by twogee** [comment]
Sorry for getting carried away with diamonds 😃... I put back
`assertFalse(moduleId.equals(null));`
but that assertion is equivalent to
`assertFalse(null instanceOf ModuleId)`
which is always true, isn't it?

**Comment by janmaterne** [comment]
Nop ... yes. You're right with 'null instanceof SomeClass'==true.
But the two assertions are different:
moduleId = null;
assertFalse(moduleId.equals(null);; --> this will throw a NullPointerException

**Comment by twogee** [comment]
That's exactly why I introduced assertNotNull :-)

**Comment by twogee** [comment]
I mean, why use an NPE when one can have an assertion that fails? It's a cleaner approach.

**Comment by janmaterne** [comment]
Merged that, thanks.
Hint for future PRs: smaller are better (easier to review)

**Pull request merged**
