### PR TITLE
Replace emma with jacoco

### PR DESCRIPTION
**Pull request by twogee**
This modernises the reporting of code coverage.
Please try it out.
NB! On macOS, it tickles https://bugs.openjdk.java.net/browse/JDK-8022291
which is harmless, currently slated for fix in JDK9

### CODE REVIEW

**Comment by twogee** [comment]
P.S. Any suggestions about finding out which rules do not work in Checkstyle are much appreciated. I had to resort to trial and error.

Also, Ant includes a [different variant](https://github.com/apache/ant/blob/master/src/etc/checkstyle/checkstyle-frames.xsl) of `checkstyle-frames.xsl`; perhaps it would make sense to keep them in sync.

**Comment by janmaterne** [comment]
The JaCoCo 'logfile' seems to be a binary one. So it should not be named '*.log'. Maybe 'jacoco-log.bin'?

In 'test-report' the <fail> should be the last statement, so we get the report created.

Running the jacoco:report gives me an error:
  java.lang.IncompatibleClassChangeError: 
      class org.jacoco.core.internal.flow.ClassProbesVisitor has interface org.objectweb.asm.ClassVisitor as super class
  ...
  at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1149)
  at java.lang.ClassLoader.loadClass(Unknown Source)
  at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:563)
  at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
  at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)

Sync: we should think about having not only the xsl in sync. Also the checkstyle rules.

Finding the CS rules: I also used trial&error: deactivate all rules and activate one after the other. (maybe several at once).

**Comment by twogee** [comment]
By default, jacoco "log" gets extension ".exec"; I'd rather call it ".data". I can amend the PR later tonight.

Could you please check your classpath for multiple instances of asm? jacoco needs the latest asm (5.2).

**Comment by twogee** [comment]
JaCoCo "log" gets an extension ".data";
JaCoCo reports are generated when JUnit fails;
Checkstyle rules sync'ed with Ant.
Anything else?

I found out that JUnit tests polute run.classpath by placing an empty jar in /lib, which breaks eg javadoc. Any ideas which test may do that?

**Comment by jaikiran** [comment]
>> I found out that JUnit tests polute run.classpath by placing an empty jar in /lib, which breaks eg javadoc. Any ideas which test may do that?

I believe this PR https://github.com/apache/ant-ivy/pull/37 will address that issue

**Comment by nlalevee** [comment]
The build-release.xml seems to be largely modified because of some space at the end of xml tags. Could we avoid that ? It is painful to review and seems useless.

**Comment by twogee** [comment]
Revised accordingly.

**Comment by janmaterne** [comment]
First progress: found an old ASM on Ant's own classpath. Ant 1.9.6 loads that via fetch.xml. Different topic ...

JaCoCo runs fine. Report generation failed without any hint. Try running with -debug ...

**Comment by twogee** [comment]
There are reports about the "log" file getting corrupt when it accumulates results from multiple runs. If 'ant clean' helps, then perhaps the "log" file must be removed in test-internal target before any tests are executed.

**Comment by janmaterne** [comment]
Stacktrace is:
C:\projekte\apache-ant\ivy-core\build.xml:492: Error while creating report
        at org.jacoco.ant.ReportTask.execute(ReportTask.java:501)
Caused by: java.io.IOException: Error while analyzing org\apache\ivy\Ivy$1.class.
        at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:155)
Caused by: java.lang.IllegalStateException: Can't add different class with same name: org/apache/ivy/Ivy$1
        at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:107)

I'll try a clean+test-report ...

**Comment by janmaterne** [comment]
While not having the result of the clean-run, what about deleting the jacoco.data file just before running <jacoco>?

With ASM I could spend a little bit to do a check before ... (something like: rc = all jars with name = *asm*.jar and a loadable ASM.class; if rc.length>1 fail)

**Comment by janmaterne** [comment]
Adressed the deletion by myself.
Left the ASM over for another time.
Merge all ...

**Comment by twogee** [comment]
Thanks! BTW I had to keep the "test-coverage" target as an alias because that's what the Jenkins scripts expect. That's another adjustment for later...

**Pull request merged**
