### PR TITLE
IVY-1321 Make Main.run() public

### PR DESCRIPTION
**Pull request by twogee**
Inspired by #69

### CODE REVIEW

**Comment by twogee** [comment]
This addresses IVY-1321 and IVY-1578

**Comment by supertick** [comment]
I agree @twogee  now that I've seen your change, your solution would be better.  
I felt too,  adding a new command line option was not the best, but also felt strongly, with minimal work the standalone interface could be supported.  I'm glad your change supports the interface without the additional option.

Now perhaps these https://www.google.com/search?q=ivy+programmatic+stackoverflow 
can be answered simply with 

```
try {
    CommandLineParser parser = getParser();
    // parse the command line arguments	  
    CommandLine line = parser.parse(args);	         
    ResolveReport  report = Main.run(line, false);
    // iterate through the report
} catch (Exception e) {
    // do something to handle error
}
```

Thanks.

**Comment by twogee** [comment]
Actually, you should be able to do

```
try {
    ResolveReport  report = Main.run(args, false);
    // iterate through the report
} catch (Exception e) {
    // do something to handle error
}
```

But, I was hasty and the tests still fail. I'll try to rectify that later today.

**Comment by twogee** [comment]
I'm a bit surprised that StackOverflow does not refer to Apache [Confluence](https://cwiki.apache.org/confluence/display/IVY/Programmatic+use+of+Ivy)

**Comment by twogee** [comment]
@supertick if you're fine with this PR, please close #69. I will merge this one later.

**Comment by supertick** [comment]
I would make a default overload which took only a String[] arg to model **exactly** the Main.main input, but all the rest is perfect, including the better isCli boolean vs silly cli option

ResolveReport report = Main.run(new String[]{ .... exact standalone api ... })

I would leave the Exception throws signature in the overloaded run method...

Thanks for your consideration, work, and mention ;) !
Cheers !

**Comment by twogee** [comment]
Thanks for bearing with me 😉please see the revised commit.

**Comment by supertick** [comment]
Looks great !
(had to look up what REPL is - thanks for the heads up)

**Pull request closed without merging**
