### PR TITLE
Convert tests to JUnit 4, clean up code

### PR DESCRIPTION
**Pull request by twogee**
JUnit 4 has primarily two benefits, clarity through annotations and more fine grained control of failures

### CODE REVIEW

**Comment by janmaterne** [comment]
That was a lot of work (or writing/using a transformator ;)
Basically it
- removes the "extends TestCase" and
- uses JUnit annotations
- change string.indexOf()!=-1 to string.contains()
- use foreach instead of for-i
- small improvements
- spell check

test/java/org/apache/ivy/ant/IvyCacheFilesetTest.java
In testFailure() you use @Test(expect=BuildException.class). Therefor the last fail() statement is obsolete.

This pattern occurs several more times. 
Could you change that?

Nice use of @Rule ExpectedException in IvyCleanCacheTest.
Could you use that in IvyConfigureTest#testOverrideNotAllowed() and Co?

**Comment by twogee** [comment]
Thanks for a nice summary and pointing out a paradigm that I did not investigate entirely. The essential work also included checking that all appropriate setUp() and tearDown() were public and/or necessary.

**Comment by twogee** [comment]
I left a few `fail()`s where multiple assertions were made; I guess that requires a custom @Rule.

Also, in `FileSystemResolverTest`, I moved `finally` blocks to `tearDown()`. Strangely, that caused failures in `testPublishTransactionWithDottedOrganisation()` because of leftover files, so I added extra cleanup in `tearDown()`.

**Comment by janmaterne** [comment]
Nice idea to use the old fail-Message as new method comment to document why the exception is expected.

**Comment by janmaterne** [comment]
merged, thanks

**Comment by nlalevee** [comment]
@twogee to properly add you to the list of contributors, do you confirm you are 
Gintautas Grigelionis ?

**Comment by twogee** [comment]
I do 😃

**Pull request merged**
